# Generated by Django 3.1.3 on 2020-11-23 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_actiive',
            new_name='is_active',
        ),
    ]
